### STAGE 1: BUILD ###
FROM node:18.12 AS build
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend/ ./
RUN npm run build

### STAGE 2: NGINX ###
FROM nginx:1.22 as production
WORKDIR /app
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY --from=build /app/conf/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]