version: "3"
services:
  mongodb:
    image: "mongo:latest"
    # the port that we want to publish for mongodb
    ports:
      - "27017:27017"
    # our mongodb depends on volume to keep the data alive.
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "testing123"
    networks:
      - internal-proxy
  redis:
    image: "redis:7.0"
    expose:
      - "6379"
    networks:
      - internal-proxy
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    networks:
      - external-proxy
      - internal-proxy
    ports:
      - "3001:3001"
    command: npm start
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    networks:
      - external-proxy

networks:
  external-proxy:
    external: true
  internal-proxy:
    external: false

volumes:
  mongo-data:
    external: false
