version: "3"
services:
  redis:
    image: "redis:7.0"
    expose:
      - "6379"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    command: npm run dev
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
