version: "3"
services:
  redis:
    image: "redis:7.0"
    expose:
      - "6379"
    networks:
      - internal-proxy
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    networks:
      - external-proxy
    ports:
      - "3001:3001"
    command: npm start
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    networks:
      - external-proxy

networks:
  external-proxy:
    external: true
  internal-proxy:
    external: false
