export const USER_FETCH = "USER_FETCH";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";

// Profile attributes
export const ADD_USER_LIKE = "ADD_USER_LIKE";
export const DELETE_USER_LIKE = "DELETE_USER_LIKE";

export const ADD_USER_DISLIKE = "ADD_USER_DISLIKE";
export const DELETE_USER_DISLIKE = "DELETE_USER_DISLIKE";

export const ADD_USER_SOCIAL_MEDIA = "ADD_USER_SOCIAL_MEDIA";
export const DELETE_USER_SOCIAL_MEDIA = "DELETE_USER_SOCIAL_MEDIA";

export const TOGGLE_USER_FAVORITE = "SET_USER_FAVORITE";
