export const ADD_POKEMON_TO_TEAM = "ADD_POKEMON_TO_TEAM";
export const REMOVE_POKEMON_FROM_TEAM = "REMOVE_POKEMON_FROM_TEAM";
export const CREATE_TEAM = "CREATE_TEAM";
export const SET_SELECTED_TEAM = "SET_SELECTED_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
